# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    id: "ecsher"
    binary: ecsher
    ldflags:
     - -s -w
     - -X github.com/Mic-U/ecsher/cmd.EcsherVersion={{.Version}}
     - -X github.com/Mic-U/ecsher/cmd.Revision={{.ShortCommit}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  prerelease: auto
brews:
  - 
    name: ecsher
    tap:
      owner: Mic-U
      name: homebrew-ecsher
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/Mic-U/ecsher/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    folder: Formula
    homepage: "https://github.com/Mic-U/ecsher"
    description: "CLI tool describing ECS resources like kubectl written in Go"
    license: "Apache-2.0"
    install: |
      bin.install "ecsher"